# Generated by Django 3.2.4 on 2021-06-13 10:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('ELECTRONICS', 'Electronic goods'), ('FROZEN_FOOD', 'Frozen items like ice creams'), ('MEAT', 'Raw meats'), ('FRUITS', 'Fruits'), ('CANNED_GOODS', 'Canned goods like cool drinks'), ('SNACKS', 'Snacks items'), ('CEREAL', 'Cereals like black grams'), ('PERSONAL_CARE', 'Personal care items like soaps'), ('HOUSEHOLD_ITEMS', 'Day to day items'), ('OTHERS', 'Other items')], default='OTHERS', max_length=20)),
                ('cost_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('profit', models.FloatField()),
                ('expiry_date', models.DateField(default=None)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
