# Generated by Django 3.2.4 on 2021-06-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_type',
            field=models.CharField(choices=[('COUNT', 'Count of item'), ('GRAM', 'Grams'), ('MILLI_GRAM', 'Milli grams'), ('LITRE', 'Litre'), ('MILLI_LITRE', 'Milli litre')], default='COUNT', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ELECTRONICS', 'Electronic goods'), ('FROZEN_FOOD', 'Frozen items'), ('MEAT', 'Raw meat'), ('FRUITS', 'Fruits'), ('CANNED_GOODS', 'Canned goods'), ('SNACKS', 'Snacks items'), ('CEREAL', 'Cereals'), ('PERSONAL_CARE', 'Personal care items'), ('HOUSEHOLD_ITEMS', 'Day to day items'), ('OTHERS', 'Other items')], default='OTHERS', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='profit',
            field=models.FloatField(null=True),
        ),
    ]
