# Generated by Django 3.2.4 on 2021-06-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auto_20210613_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='profit',
            field=models.FloatField(default=None),
        ),
    ]
