# Generated by Django 3.2.4 on 2021-06-13 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_auto_20210613_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2048, 10, 29, 16, 57, 33, 14195)),
        ),
        migrations.AlterField(
            model_name='product',
            name='profit',
            field=models.FloatField(default=None),
        ),
    ]
