# Generated by Django 3.2.4 on 2021-06-13 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_auto_20210613_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2048, 10, 29, 16, 59, 12, 490505)),
        ),
        migrations.AlterField(
            model_name='product',
            name='profit',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
