# Generated by Django 3.2.4 on 2021-06-15 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_alter_product_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2048, 10, 31)),
        ),
    ]
